[package]
name = "curator_sketch"
version = "0.0.0"
authors = ["Arnau Siches <asiches@gmail.com>"]
edition = "2018"
description = "A library to sketch ideas for Curator."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
